spring.application.name=demo6

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/book_testing_api
spring.datasource.username=root
spring.datasource.password=tittom343

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Encoding
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4